
# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'muglug'

branding:
  icon: 'check'
  color: 'blue'

description: 'Run Psalm via GitHub Actions'

name: 'Psalm – Static Analysis for PHP'

inputs:
  security_analysis:
    required: false
    default: false
    description: 'Whether or not to use Psalm’s security analysis'
  report_file:
    required: false
    default: ''
    description: 'File for Psalm’s output'
  composer_require_dev:
    required: false
    default: false
    description: 'Whether or not Composer installs dev packages'
  composer_ignore_platform_reqs:
    required: false
    default: false
    description: 'Whether or not the --ignore-platform-reqs flag is passed to Composer'

runs:
  using: 'docker'
  image: 'Dockerfile'
