
# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'muglug'

branding:
  icon: 'check'
  color: 'blue'

description: 'Run Psalm via GitHub Actions'

name: 'Psalm Static Analysis'

runs:
  using: 'docker'
  image: 'docker://vimeo/psalm-github-actions'
